
trigger:
  - master
  
pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js 16.x'

      - script: |
          cd fieldSparkBo/
          npm install -g @angular/cli
          npm install
          ng build
        displayName: 'npm install and build'
        workingDirectory: '$(Build.SourcesDirectory)'

- stage: QA
  displayName: 'Deploy QA'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentQA
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              submodules: 'true'
            - task: AzureStaticWebApp@0
              inputs:
                app_location: "/"
                api_location: ""
                output_location: "dist/"
              env:
                azure_static_web_apps_api_token: $(deployment_token)